[drop_pool.gem_basic]
entries = [
  { tag = "active_skill_gem", weight = 300 },
  { tag = "passive_skill_gem", weight = 200 },
  { tag = "support_gem", weight = 500 },
]

[drop_pool.active_skill_gems]
entries = [
  { id = "active_split_firebolt", weight = 100 },
  { id = "active_ice_shot", weight = 100 },
  { id = "active_chromatic_shot", weight = 100 },
  { id = "active_whirlwind", weight = 100 },
  { id = "active_stoneskin", weight = 100 },
  { id = "active_thundercloud", weight = 100 },
  { id = "active_blizzard", weight = 100 },
  { id = "active_chain_lightning", weight = 100 },
  { id = "active_ring_of_ice", weight = 100 },
  { id = "active_flame_slash", weight = 100 },
  { id = "active_lightning_shot", weight = 100 },
  { id = "active_corrosive_shot", weight = 100 },
  { id = "active_burning_shot", weight = 100 },
  { id = "active_rain_of_arrows", weight = 100 },
  { id = "active_sparkle", weight = 100 },
  { id = "active_black_hole", weight = 100 },
]

[drop_pool.support_gems]
entries = [
  { tag = "gem_type_3", weight = 220 },
  { tag = "gem_type_4", weight = 300 },
  { tag = "gem_type_5", weight = 160 },
  { tag = "gem_type_6", weight = 140 },
  { tag = "gem_type_7", weight = 80 },
  { tag = "gem_type_8", weight = 100 },
  { tag = "gem_type_9", weight = 100 },
]

[drop_pool.passive_skill_gems]
entries = [
  { id = "passive_weapon_amplification", weight = 100 },
  { id = "passive_spell_amplification", weight = 100 },
  { id = "passive_precise_projectiles", weight = 100 },
  { id = "passive_fearless", weight = 100 },
  { id = "passive_rejuvenation", weight = 100 },
  { id = "passive_energy_fortress", weight = 100 },
  { id = "passive_electric_conversion", weight = 100 },
  { id = "passive_frigid_domain", weight = 100 },
  { id = "passive_magical_source", weight = 100 },
]
